name: GSA-WA2025
channels:
  - conda-forge
dependencies:
  - python==3.12
  - geopandas==0.14.4
  - pygmt==0.11
  - GMT
  - openpyxl
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - cartopy
  - tqdm
  - scipy
  - pip
  - pip:
    - pyrolite
    - xlrd
