name: pygmt-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pygmt=0.11.0
  - geopandas=0.14.4
  - pandas=2.0.0
  - numpy=1.26.4
  - matplotlib
  - seaborn=0.12.1
  - scikit-learn=1.7.0
  - cartopy=0.24.1
  - tqdm
  - scipy=1.10
  - pip
  - pip:
      - pyrolite==0.3.5
      - xlrd==2.0.1
