name: pygmt-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pygmt=0.11.0
  - geopandas=0.14.4
  - pandas=2.0.0
  - numpy=1.26.4
  - matplotlib
  - seaborn=0.13.2
  - scikit-learn=1.7.0
  - cartopy
  - tqdm
  - scipy=1.10
  - mpltern
  - scikit-bio
  - plotly
  - plotly-express
  - pip
  - pip:
      - pyrolite==0.3.5
      - xlrd==2.0.1
      - openpyxl
